config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tip_of_the_days
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
      get 'products/statistics' => 'products#statistics'
      resources :products
      resources :categories
      resources :plans
      resources :temp_products
      post 'temp_products/submit' => 'temp_products#submit'
      namespace :api do
        resources :search, only: [:index]
      end

      get 'schedules/recurring_expenses' => 'schedules#recurring_expenses'
      get 'schedules/list' => 'schedules#list'
      resources :schedules

      resources :comments, except: %i[new edit update show destroy index]
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/temp_product.rb
class TempProduct < ApplicationRecord
  validates :name, length: { in: 2..100 }
  validates :category, presence: true
  validates :quantity, presence: true, numericality: { other_than: 0 }
end

app/controllers/temp_products_controller.rb
require_relative '../providers/temp_product_provider.rb'

class TempProductsController < ApplicationController
  def index
    @choices = []
    Category.where(user_id: current_user.id).each do |c|
      @choices.push(c.name)
    end
    @choice = @choices.first

    @temp_products = TempProduct.where(user_id: current_user.id)
  end

  def submit
    json_data = JSON.parse(params.require(:temp_products_json)[:json_data])

    json_data.each do |item|
      temp_id = item['id']

      item.delete('id')
      item.delete('created_at')
      item.delete('updated_at')

      product = Product.new(item)

      if product.save
        flash[:notice] = 'Product(s) added'
      else
        flash[:notice] = 'Product(s) adding failed'
        redirect_to action: 'index'
        return
      end

      temp_product = TempProduct.where(user_id: current_user.id).find(temp_id.to_i)
      temp_product.destroy
    end
    redirect_to action: 'index'
  end

  def create
    @temp_product = TempProduct.new(temp_product_params)
    @temp_product.category = params[:category]
    @temp_product.user_id = current_user.id

    flash[:notice] = if @temp_product.save
                       'Product added'
                     else
                       'Product adding failed'
                     end

    redirect_to action: 'index'
  end

  def edit
    @temp_product = TempProduct.where(user_id: current_user.id).find(params[:id])
    @choices = []
    Category.where(user_id: current_user.id).each do |c|
      @choices.push(c.name)
    end
    @choice = @temp_product.category
  end

  def update
    @temp_product = TempProduct.where(user_id: current_user.id).find(params[:id])
    @temp_product.category = params[:category]
    if @temp_product.update(temp_product_params)
      flash[:notice] = 'Product updated'
      redirect_to action: 'index'
    else
      flash[:notice] = 'Product updating failed'
      render action: 'edit'
    end
  end

  def destroy
    @temp_product = TempProduct.where(user_id: current_user.id).find(params[:id])
    @temp_product.destroy
    redirect_to temp_products_path
  end

  def temp_product_params
    params.require(:temp_product).permit(:name, :category, :quantity)
  end
end

app/helpers/temp_products_helper.rb
module TempProductsHelper
end

app/views/temp_products/_form.html.slim
.container
  .col
    .card-body.bg-light
      -if !@temp_products
        h1 Edit Product from Shopping List
        form
        = form_for @temp_product do |f|
          br
          .form-group
            = f.label :name,'Name'
            br
            = f.text_field :name, class: 'form-control', placeholder: 'Bread'
          .form-group
            = f.label :category,'Category'
            br
            = select_tag :category, options_for_select(@choices, @choice), class: 'form-control'
          .form-group
            = f.label :quantity,'Quantity'
            br
            = f.text_field :quantity, class: 'form-control', placeholder: '2'
          br
          = f.submit "Edit Product", class: 'btn btn-lg btn-primary btn-block'
      -else
        h1 Shopping List
        form
        = form_for :temp_product, url: temp_products_path do |f|
          br
          .form-group
            = f.label :name,'Name'
            br
            = f.text_field :name, class: 'form-control', placeholder: 'Bread'
          .form-group
            = f.label :category,'Category'
            br
            = select_tag :category, options_for_select(@choices, @choice), class: 'form-control'
          .form-group
            = f.label :quantity,'Quantity'
            br
            = f.text_field :quantity, class: 'form-control', placeholder: '2'
          br
          = f.submit "Add Product", class: 'btn btn-lg btn-primary btn-block'

app/views/temp_products/edit.html.slim
render = render partial: "form"

app/views/temp_products/index.html.slim
render = render partial: "form"
br
.card-body.bg-light 
  .row
    .col-md-3
    #table-responsive.col-6
      table.table.table-light
        thead
          tr
            th
            th
            th Name
            th Category
            th Quantity
            th
        tbody
          - @temp_products.reverse.each do |temp|
            tr
              td
              td 
                input.form-check-input.temp-check id="check#{temp.id}" type="checkbox"
              td = temp.name
              td = temp.category
              td = temp.quantity
              td
                =link_to "Edit", edit_temp_product_path(temp), 
                                  :style =>"margin: 10px",
                                  class: 'btn btn-outline-info'
                =link_to "Delete", temp_product_path(temp),
                                    method: :delete, data:{confirm: 'Are you sure?'},
                                    :style =>"margin: 10px", class: 'btn btn-outline-danger'
            td colspan="6" id="form#{temp.id}" style="display: none"
              input.form-control id="input_price#{temp.id}" placeholder=("Price")
          tr
            td colspan="6"
              center
                form
                = form_for :temp_products_json, url: temp_products_submit_path do |f|
                  .form-group
                    = f.hidden_field :json_data, :value => TempProductProvider.get_json(current_user.id), :id => 'json_data_input'
                    = f.label :shop, 'Shop name'
                    br
                    input.form-control id="input_shop" placeholder=("Tesco")
                  br
                  = f.submit "Add to products", class: 'btn btn-lg btn-primary btn-block', id: 'temp_submit'