config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tip_of_the_days
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
      get 'products/statistics' => 'products#statistics'
      resources :products
      resources :categories
      resources :plans
      resources :temp_products
      post 'temp_products/submit' => 'temp_products#submit'
      namespace :api do
        resources :search, only: [:index]
      end

      get 'schedules/recurring_expenses' => 'schedules#recurring_expenses'
      get 'schedules/list' => 'schedules#list'
      resources :schedules

      resources :comments, except: %i[new edit update show destroy index]
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index; end

  def recurring_expenses
    @period = (params[:period] || ProductProvider.dates[0])
    @products = Product.where(user_id: current_user.id).order('created_at')
    @products = @products.where('created_at > ?', ProductProvider.date_selector(@period)) if @period != 'All'
    @choices = []
    Category.where(user_id: current_user.id).each do |c|
      @choices.push(c.name)
    end
    @choice = @choices.first
  end

  def destroy
    Product.delete_delay_job(params[:id], current_user.id)
    redirect_to schedules_list_path
  end

  def list
    @jobs = Delayed::Job.where('run_at >= NOW()')
                        .where('attempts = 0')
                        .where('locked_at IS NULL')
                        .where('locked_by IS NULL')
                        .where('failed_at IS NULL')
    result = []
    @jobs.each do |job|
      result.push(job.payload_object.args.unshift(job.id)) if job.payload_object.args[1] == current_user.id
    end
    @jobs = result
  end

  def create
    period = params[:period]
    date = params[:schedule][:date]
    new_params = params[:schedule]
    new_params.delete(:date)
    new_params[:category] = params[:category]
    params = new_params
    Product.delay(run_at: date).create_delay_job(params, current_user.id, period, date)
    flash[:notice] = 'Recurring expense added'
    redirect_to schedules_list_path
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.slim
.card-body.bg-light
  h1 Adding recurring expense
  form
  = form_for :schedule, url: schedules_path do |f| 
    .form-group
      = label :period,'Period'
      = select_tag :period, options_for_select(ProductProvider.dates[0..-2].unshift("Day"), @period),
                            class: 'form-control'
    .form-group
      = f.label :date,'Date'
      br
      = f.text_field :date, class: 'form-control', placeholder: 'rrrr-mm-dd'
    .form-group
      = f.label :name,'Name'
      br
      = f.text_field :name, class: 'form-control', placeholder: 'Name'
    .form-group
      = f.label :shop,'Shop'
      br
      = f.text_field :shop, class: 'form-control', placeholder: 'Shop'
    .form-group
      = f.label :category,'Category'
      br
      = select_tag :category, options_for_select(@choices, @choice), class: 'form-control'
    .form-group
      = f.label :price,'Price'
      br
      = f.text_field :price, class: 'form-control', placeholder: 'Price'
    .form-group
      = f.label :quantity,'Quantity'
      br
      = f.text_field :quantity, class: 'form-control', placeholder: 'Quantity'
    br
    = f.submit "Save Product", :style =>"width: 300px", class: 'btn btn-lg btn-primary btn-block'

app/views/schedules/index.html.slim
.row
  .col-12.col-md-4.text-center
    =link_to schedules_recurring_expenses_path do
      = image_tag  'shopping-icon.png'
    h3 Recurring Expenses
  .col-12.col-md-4.text-center
    =link_to schedules_list_path do
      = image_tag  'shopping-icon.png'
    h3 Recurring Expenses List
  .col-12.col-md-4.text-center
    =link_to plans_path do
      = image_tag  'shopping-icon.png'
    h3 Planning

app/views/schedules/list.html.slim
table.table.table-light
  thead
    tr
      th Name
      th Shop
      th Price
      th Quanity
      th Category
      th Period
      th Next date
      th Option
  tbody
  - @jobs.reverse.each do |job|
    tr
    - job[1].each do |key, val|
      td = val
    td
      = job[3]
    td
      = job[4]
    td 
      = link_to "Delete", schedule_path(:id => job[0]),
                          method: :delete, data:{confirm: 'Are you sure?'},
                          :style =>"margin: 10px", class: 'btn btn-outline-danger'

app/views/schedules/recurring_expenses.html.slim
render = render partial: "form"