config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tip_of_the_days
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
      get 'products/statistics' => 'products#statistics'
      resources :products
      resources :categories
      resources :plans
      resources :temp_products
      post 'temp_products/submit' => 'temp_products#submit'
      namespace :api do
        resources :search, only: [:index]
      end

      get 'schedules/recurring_expenses' => 'schedules#recurring_expenses'
      get 'schedules/list' => 'schedules#list'
      resources :schedules

      resources :comments, except: %i[new edit update show destroy index]
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, length: { in: 2..100 }
  validates :shop, length: { in: 2..100 }
  validates :category, presence: true
  validates :price, presence: true
  validates :quantity, presence: true, numericality: { other_than: 0 }

  include PgSearch
  pg_search_scope :search, against: :name,
                           using: {
                             tsearch: { prefix: true, dictionary: 'english' }
                           }

  def values
    vals = []
    attributes.values[1..-3].each do |x|
      vals.push((x.is_a?(Float) ? format('%.2f', x) : x))
    end
    vals
  end

  def read_comment
    comment = Comment.where(product_id: id)
    if comment[0]
      comment[0].content
    else
      ''
    end
  end

  def self.create_delay_job(params, u_id, period, date)
    Product.create(name: params[:name],
                   shop: params[:shop],
                   category: params[:category],
                   price: params[:price].to_f,
                   quantity: params[:quantity].to_i,
                   user_id: u_id)

    new_date = ProductProvider.calculate_date(date, period)
    delay(run_at: new_date).create_delay_job(params, u_id, period, new_date)
  end

  def self.delete_delay_job(job_id, u_id)
    job = Delayed::Job.find(job_id)
    job.delete if job.payload_object.args[1] == u_id
  end

  def self.categories_names
    names = []
    all.column_names[1..-3].each do |name|
      names.push(name.capitalize.tr('_', ' '))
    end
    names
  end

  def self.total_price
    total = 0
    all.each { |product| total += product.price * product.quantity }
    total
  end

  def self.total_price_by_category
    total = {}
    all.each do |product|
      total[product.category] = 0
      total[product.category] += product.price * product.quantity
    end
    total
  end
end

app/controllers/products_controller.rb
require_relative '../providers/product_provider.rb'
require_relative '../providers/report_provider.rb'

class ProductsController < ApplicationController
  before_action :select_categories

  def index
    @period = (params[:period] || ProductProvider.dates[0])
    @products = Product.where(user_id: current_user.id).order('created_at')
    @products = @products.where('created_at > ?', ProductProvider.date_selector(@period)) if @period != 'All'
  end

  def statistics
    @period = (params[:period] || ProductProvider.dates[0])
    @categories = Category.where(user_id: current_user.id)
    @products = Product.where(user_id: current_user.id).order('created_at')
    @products = @products.where('created_at > ?', ProductProvider.date_selector(@period)) if @period != 'All'
  end

  def new; end

  def create
    @product = Product.new(product_params)
    @product.category = params[:category]
    @product.user_id = current_user.id

    if @product.save
      ReportProvider.check_plans(current_user.id)
      flash[:notice] = 'Product added'
      redirect_to action: 'index'
    else
      flash[:notice] = 'Product adding failed'
      render action: 'new'
    end
  end

  def edit
    @product = Product.where(user_id: current_user.id).find(params[:id])
    @choice = @product.category
  end

  def update
    @product = Product.where(user_id: current_user.id).find(params[:id])
    @product.category = params[:category]
    if @product.update(product_params)
      ReportProvider.check_plans(current_user.id)
      flash[:notice] = 'Product updated'
      redirect_to action: 'index'
    else
      flash[:notice] = 'Product updating failed'
      render action: 'edit'
    end
  end

  def destroy
    @product = Product.where(user_id: current_user.id).find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :shop, :category, :price, :quantity)
  end

  def select_categories
    @choices = []
    Category.where(user_id: current_user.id).each do |c|
      @choices.push(c.name)
    end
    @choice = @choices.first
  end
end

app/views/products/_form.html.slim
.card-body.bg-light
    -if @product
        h1 Editing a product
        form
        = form_for @product do |f| 
            .form-group
                = f.label :name,'Name'
                br
                = f.text_field :name, class: 'form-control', placeholder: 'Name'
            .form-group
                = f.label :shop,'Shop'
                br
                = f.text_field :shop, class: 'form-control', placeholder: 'Shop'
            .form-group
                = f.label :category,'Category'
                br
                = select_tag :category, options_for_select(@choices, @choice), class: 'form-control'
            .form-group
                = f.label :price,'Price'
                br
                = f.text_field :price, class: 'form-control', placeholder: 'Price'
            .form-group
                = f.label :quantity,'Quantity'
                br
                = f.text_field :quantity, class: 'form-control', placeholder: 'Quantity'
            br
            = f.submit "Save Product", :style =>"width: 300px", class: 'btn btn-lg btn-primary btn-block'
           
    -else
        h1 Adding a product
        form
        = form_for :product, url: products_path do |f| 
            .form-group
                = f.label :name,'Name'
                br
                = f.text_field :name, class: 'form-control', placeholder: 'Name'
            .form-group
                = f.label :shop,'Shop'
                br
                = f.text_field :shop, class: 'form-control', placeholder: 'Shop'
            .form-group
                = f.label :category,'Category'
                br
                = select_tag :category, options_for_select(@choices, @choice), class: 'form-control'
            .form-group
                = f.label :price,'Price'
                br
                = f.text_field :price, class: 'form-control', placeholder: 'Price'
            .form-group
                = f.label :quantity,'Quantity'
                br
                = f.text_field :quantity, class: 'form-control', placeholder: 'Quantity'
            br
            = f.submit "Save Product", :style =>"width: 300px", class: 'btn btn-lg btn-primary btn-block'
            br
            = link_to "+Add category", categories_path, :style =>"width: 300px", class: 'btn btn-lg btn-secondary btn-block'

app/views/products/edit.html.slim
render = render partial: "form"

app/views/products/index.html.slim
.card-body.bg-light 
  .row
    .col-md-2
    #table-responsive.col-8
      h1 Your products
      .form-inline.my-2.my-lg-0.search-form.float-right
       input.main-search.form-control.mr-sm-2#search type="search" placeholder="Search" aria-label="Search"
      p
       = 'Money spent: ' + ("%.2f" % [@products.total_price])
      
      = form_for :period, url: products_path, method: 'get' do
        = label :period,'Select desired period'
        = select_tag :period, options_for_select(ProductProvider.dates, @period),
                              class: 'form-control',
                              :onchange => 'this.form.submit();'
      br
      table.table.table-light
        thead
          tr
          - @products.categories_names.each do |x|
            th = x
          th Options
        tbody#products
          - @products.reverse.each do |product|
            tr id=product.id
              - product.values.each do |x|
                td = x
              td
                = form_for :comment, :html => { :id => 'comment'+product.id.to_s }, url: comments_path do |f|
                  = f.hidden_field :id, :value => product.id.to_s
                  = f.hidden_field :text, :value => product.read_comment
                  = f.button 'Comment', :style => 'margin: 10px',
                                        class: 'btn btn-outline-info',
                                        :onclick => 'comment('+product.id.to_s+');',
                                        :title => product.read_comment
                  =link_to "Edit", edit_product_path(product), 
                                      :style =>"margin: 10px",
                                      class: 'btn btn-outline-info'
                  =link_to "Delete", product_path(product),
                                      method: :delete, data:{confirm: 'Are you sure?'},
                                      :style =>"margin: 10px", class: 'btn btn-outline-danger'
.col-md-2

app/views/products/new.html.slim
render = render partial: "form"

app/views/products/statistics.html.slim
= stylesheet_link_tag 'statistics'

.card-body.bg-light 
  .row
    .col-md-2
    #table-responsive.col-8
      = form_for :period, url: products_statistics_path, method: 'get' do
          #select_date
            = label :period,'Select desired period'
          = select_tag :period, options_for_select(ProductProvider.dates, @period),
                                class: 'form-control',
                                :onchange => 'this.form.submit();'
      br
      br
    #total
      = 'Total: ' + ("%.2f" % [@products.total_price])
    #total_category
      - @products.total_price_by_category.each do |key, value|
        div
          = key + ": "+("%.2f" % [value])

= content_tag "div", "", id: 'categories', data: { categories: @categories }
= content_tag "canvas", "", id: 'myChart', data: { products: @products }