config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tip_of_the_days
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
      get 'products/statistics' => 'products#statistics'
      resources :products
      resources :categories
      resources :plans
      resources :temp_products
      post 'temp_products/submit' => 'temp_products#submit'
      namespace :api do
        resources :search, only: [:index]
      end

      get 'schedules/recurring_expenses' => 'schedules#recurring_expenses'
      get 'schedules/list' => 'schedules#list'
      resources :schedules

      resources :comments, except: %i[new edit update show destroy index]
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_alerts.html.slim
- if notice
  .alert.alert-warning
    a.close aria-label='close' data-dismiss='alert' href='#'  × 
    = notice
- if alert
  .alert.alert-warning
    a.close aria-label='close' data-dismiss='alert' href='#'  ×
    = alert

- @reports.each do |r|
  .alert.alert-info
    a.close aria-label='close' data-dismiss='alert' href='#' onclick='$.ajax({url: "/delete_report", method: "delete", data: {id:#{r.id}}});'  ×
    = r.msg

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    = stylesheet_link_tag 'application',                                    \
                          'https://fonts.googleapis.com/css?family=Montserrat', \
                          media: 'all', 'data-turbolinks-track' => true  
    title PersonalFinances
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    nav.navbar.navbar-expand-lg.navbar-light.bg-light
      = link_to("Personal Finances >", authenticated_root_url, :class => "navbar-brand pl-3", :style=>"font-size: 30px;")
      button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
        span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        ul.navbar-nav.ml-auto
          - if current_user.nil?
            li.nav-item
              = link_to("Log in", new_user_session_path, :class => "nav-link")
          - else
            li.nav-item
              = link_to("Add product", new_product_path, :class => "nav-link")
            li.nav-item
              = link_to("Products", products_path, :class => "nav-link")
            li.nav-item
              = link_to("Budgeting", schedules_path, :class => "nav-link")
            li.nav-item
              = link_to("Statistics", products_statistics_path, :class => "nav-link")
            li.nav-item
              = link_to("Shopping list", temp_products_path, :class => "nav-link")
            li.nav-item
              = link_to("Log out", destroy_user_session_path, method: :delete, :class => "nav-link")
    = render 'layouts/alerts'
    = yield